/**
 * Report Analyzer Job Handler
 *
 * Processes report_analyze jobs by emitting InspectionReportAnalyzedDraft
 * events with placeholder analysis results. In production, this would call
 * an AI service to analyze the inspection report and generate findings.
 *
 * Idempotency: Uses the job's report_id + a deterministic idempotency key
 * to ensure that retries do not create duplicate draft events.
 */

import { sql } from "drizzle-orm";
import crypto from "crypto";
import { append } from "../eventing/eventStore";
import { applyEvent } from "../projections/applyEvent";
import { EventTypes } from "../eventing/types";
import { getCurrentVersion } from "../eventing/eventStore";

type Tx = Parameters<Parameters<typeof import("../db").db.transaction>[0]>[0];

export async function handleReportAnalyze(
  tx: Tx,
  payload: Record<string, unknown>,
): Promise<void> {
  const reportId = payload.reportId as string;
  if (!reportId) throw new Error("report_analyze job requires reportId in payload");

  const row = await tx.execute(sql`
    SELECT state FROM projection_report WHERE report_id = ${reportId}
  `);
  if (row.rows.length === 0) throw new Error(`Report ${reportId} not found`);
  const state = (row.rows[0] as { state: string }).state;

  if (state !== "queued") {
    return;
  }

  const ver = await getCurrentVersion(tx, "report", reportId);
  const idempotencyKey = `report-analyze-${reportId}`;

  const draft = {
    findings: [
      {
        findingId: crypto.randomUUID(),
        title: "Placeholder finding from analysis",
        severity: "medium",
        description: "This is a placeholder finding generated by the report analyzer.",
      },
    ],
    analyzedAt: new Date().toISOString(),
  };

  const eventData = { draft };

  const result = await append(tx, {
    aggregateType: "report",
    aggregateId: reportId,
    expectedVersion: ver,
    eventType: EventTypes.InspectionReportAnalyzedDraft,
    data: eventData,
    meta: { source: "report_analyzer_worker" },
    actor: { actorType: "system", actorId: "worker" },
    idempotencyKey,
  });

  if (!result.deduped) {
    await applyEvent(tx, {
      event_seq: result.eventSeq,
      event_id: result.eventId,
      aggregate_type: "report",
      aggregate_id: reportId,
      aggregate_version: result.version,
      event_type: EventTypes.InspectionReportAnalyzedDraft,
      data: eventData as Record<string, unknown>,
      meta: { source: "report_analyzer_worker" },
      actor_type: "system",
      actor_id: "worker",
      occurred_at: new Date().toISOString(),
    });
  }
}
