/**
 * Production migration runner.
 *
 * Reads migrations/ (generated by `drizzle-kit generate`) and applies any
 * that haven't been run yet, tracked via the `drizzle.__drizzle_migrations`
 * table. Safe to run on every deploy — it's a no-op if the schema is
 * already up-to-date.
 *
 * Usage:
 *   npm run db:migrate
 *
 * Why this exists (instead of `db:push`):
 *   `drizzle-kit push` diffs the schema file against the live DB and
 *   emits destructive DDL for renames (drop column, add column). It also
 *   prompts interactively on destructive diffs, which hangs or silently
 *   fails in a non-TTY deploy container. `migrate` applies reviewed SQL
 *   files — if a migration would drop data, we see it in the generated
 *   file before it hits prod.
 *
 * Baselining:
 *   Databases that predate migration tracking (built up by `db:push`)
 *   already have every table in 0000_baseline.sql, so running that file
 *   would fail on the first CREATE TABLE. When we detect an existing,
 *   untracked database we record the baseline as applied without running
 *   it, then let the migrator apply everything after it. Fresh databases
 *   (CI, new environments) run the full chain from 0000.
 */

import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { drizzle } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { sql } from "drizzle-orm";
import pg from "pg";

const { Pool } = pg;

const MIGRATIONS_FOLDER = "./migrations";

interface JournalEntry {
  idx: number;
  when: number;
  tag: string;
}

function readJournal(): JournalEntry[] {
  const journal = JSON.parse(
    readFileSync(`${MIGRATIONS_FOLDER}/meta/_journal.json`, "utf8"),
  );
  return journal.entries as JournalEntry[];
}

/** Hash exactly the way drizzle-orm's migrator does: sha256 of the file. */
function hashMigration(tag: string): string {
  const content = readFileSync(`${MIGRATIONS_FOLDER}/${tag}.sql`, "utf8");
  return createHash("sha256").update(content).digest("hex");
}

async function main() {
  if (!process.env.DATABASE_URL) {
    // eslint-disable-next-line no-console
    console.error("DATABASE_URL is not set — cannot run migrations.");
    process.exit(1);
  }

  const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
    // Short connection timeout — migrations run at boot, and we'd rather
    // fail the deploy than hang the container waiting for a dead DB.
    connectionTimeoutMillis: 10_000,
    max: 1,
  });

  const db = drizzle(pool);

  try {
    const [baseline] = readJournal();
    if (!baseline) throw new Error("migrations/meta/_journal.json has no entries");

    await db.execute(sql`CREATE SCHEMA IF NOT EXISTS drizzle`);
    await db.execute(sql`
      CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (
        id SERIAL PRIMARY KEY,
        hash TEXT NOT NULL,
        created_at BIGINT
      )
    `);

    // The migrator applies every journal entry whose `when` is newer than
    // the last recorded created_at, so "is the baseline tracked" reduces to
    // a timestamp comparison.
    const tracked = await db.execute(sql`
      SELECT MAX(created_at)::bigint AS latest FROM drizzle.__drizzle_migrations
    `);
    const latest = Number((tracked.rows[0] as any)?.latest || 0);

    if (latest < baseline.when) {
      const existing = await db.execute(sql`SELECT to_regclass('public.users') AS t`);
      const hasAppTables = Boolean((existing.rows[0] as any)?.t);

      if (hasAppTables) {
        // eslint-disable-next-line no-console
        console.log(
          `[migrate] existing untracked database detected — recording ${baseline.tag} as applied (baselining)`,
        );
        await db.execute(sql`
          INSERT INTO drizzle.__drizzle_migrations (hash, created_at)
          VALUES (${hashMigration(baseline.tag)}, ${baseline.when})
        `);
      }
    }

    // eslint-disable-next-line no-console
    console.log("[migrate] applying migrations from ./migrations ...");
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
    // eslint-disable-next-line no-console
    console.log("[migrate] complete");
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error("[migrate] FAILED:", err);
    process.exit(1);
  } finally {
    await pool.end();
  }
}

main();
